[package]
name = "egglog_python"
version = "13.2.0"
edition = "2024"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "egglog"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module", "num-bigint", "num-rational", "indexmap"] }
num-bigint = "*"
num-rational = "*"
indexmap = "2.12"
opentelemetry = "0.28"
opentelemetry-otlp = { version = "0.28", features = ["http-proto", "reqwest-blocking-client", "trace"] }
opentelemetry-stdout = { version = "0.28", features = ["trace"] }
opentelemetry_sdk = "0.28"
# Egglog main at integration plus the rule-name round-trip fix used by this branch.
egglog = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3", default-features = false }
egglog-ast = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3" }
egglog-core-relations = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3" }
egglog-reports = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3" }
egglog-bridge = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3" }
egglog-experimental = { git = "https://github.com/egraphs-good/egglog-experimental.git", rev = "6bfb589d1c4695232fc24e9bdf097c49af451823", default-features = false }
egraph-serialize = { version = "0.3", features = ["serde", "graphviz"] }
serde_json = "1"
pyo3-log =  "*"
log = "0.4"
lalrpop-util = { version = "0.22", features = ["lexer"] }
ordered-float = "5"
tracing = "0.1"
tracing-opentelemetry = "0.29"
tracing-subscriber = "0.3"
uuid = { version = "1.18", features = ["v4"] }
base64 = "0.22.1"

# enable debug symbols for easier profiling
[profile.release]
debug = true

[patch."https://github.com/egraphs-good/egglog.git"]
egglog = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3" }
egglog-ast = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3" }
egglog-core-relations = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3" }
egglog-reports = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3" }
egglog-bridge = { git = "https://github.com/saulshanabrook/egg-smol.git", rev = "69177f4f37db9bc6c23899375988dc8b8ecedfc3" }
